# Generated by Django 3.2.10 on 2021-12-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_basic_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='staged',
            field=models.BooleanField(default=False, help_text='Content is shown in staged area', verbose_name='staged'),
        ),
        migrations.AddField(
            model_name='post',
            name='staged',
            field=models.BooleanField(default=False, help_text='Content is shown in staged area', verbose_name='staged'),
        ),
        migrations.AddField(
            model_name='publication',
            name='staged',
            field=models.BooleanField(default=False, help_text='Content is shown in staged area', verbose_name='staged'),
        ),
    ]
