# Generated by Django 3.2.10 on 2021-12-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_pagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='impressum_footer',
            field=models.TextField(blank=True, help_text='Impressum in the footer', null=True),
        ),
    ]
