# Generated by Django 3.2.10 on 2021-12-21 21:46

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='facebook',
            field=models.URLField(blank=True, help_text='Your Facebook page URL', null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='impressum',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Impressum in the footer', null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='instagram',
            field=models.CharField(blank=True, help_text='Your Instagram username, without the @', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='twitter',
            field=models.CharField(blank=True, help_text='Your Twitter username, without the @', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='youtube',
            field=models.URLField(blank=True, help_text='Your YouTube channel or user account URL', null=True),
        ),
        migrations.DeleteModel(
            name='PageSettings',
        ),
    ]
